# Site settings
title:          my bits
description:    "A gathering place for thoughts I'd like to share."
baseurl:        
url:            "https://blog.ivanbercovich.com"

# Social
twitter_username: ibercovich
linkedin_username: bercovich

# Google Analytics
# google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Ivan Bercovich
  url:          
  email:        

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year/:title.html
paginate:       20

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus: